packages:
  - apps/*
  - packages/*

catalogMode: strict

catalog:
  "@nestjs/common": 11.1.28
  "@nestjs/core": 11.1.28
  "@nestjs/platform-express": 11.1.28
  "@prisma/adapter-pg": 7.9.0
  "@prisma/client": 7.9.0
  next: 16.2.11
  pg: 8.22.0
  prisma: 7.9.0
  react: 19.2.8
  react-dom: 19.2.8
  reflect-metadata: 0.2.2
  rxjs: 7.8.2
  typescript: 5.9.3
