export const KNOWLEDGE_INGESTION_SERVICE = Symbol(
  "KNOWLEDGE_INGESTION_SERVICE",
);
export const KNOWLEDGE_RETRIEVAL_SERVICE = Symbol(
  "KNOWLEDGE_RETRIEVAL_SERVICE",
);
export const KNOWLEDGE_VECTOR_STORE = Symbol("KNOWLEDGE_VECTOR_STORE");
