export const WORKER_DATABASE_CLIENT = Symbol("WORKER_DATABASE_CLIENT");
export const COMMERCIAL_TOOL_AUDIT_REPOSITORY = Symbol(
  "COMMERCIAL_TOOL_AUDIT_REPOSITORY",
);
export const CONTENT_BRIEF_RUN_REPOSITORY = Symbol(
  "CONTENT_BRIEF_RUN_REPOSITORY",
);
export const GENERATION_RUN_REPOSITORY = Symbol("GENERATION_RUN_REPOSITORY");
export const KNOWLEDGE_DOCUMENT_REPOSITORY = Symbol(
  "KNOWLEDGE_DOCUMENT_REPOSITORY",
);
export const PUBLICATION_PRODUCTION_REPOSITORY = Symbol(
  "PUBLICATION_PRODUCTION_REPOSITORY",
);
