export const WORKER_DATABASE_CLIENT = Symbol("WORKER_DATABASE_CLIENT");
export const KNOWLEDGE_DOCUMENT_REPOSITORY = Symbol(
  "KNOWLEDGE_DOCUMENT_REPOSITORY",
);
export const PUBLICATION_PRODUCTION_REPOSITORY = Symbol(
  "PUBLICATION_PRODUCTION_REPOSITORY",
);
