export const TEXT_GENERATION_PORT = Symbol("TEXT_GENERATION_PORT");
export const STRUCTURED_GENERATION_PORT = Symbol("STRUCTURED_GENERATION_PORT");
export const IMAGE_GENERATION_PORT = Symbol("IMAGE_GENERATION_PORT");
