export const TEXT_GENERATION_PORT = Symbol("TEXT_GENERATION_PORT");
export const STRUCTURED_GENERATION_PORT = Symbol("STRUCTURED_GENERATION_PORT");
export const IMAGE_GENERATION_PORT = Symbol("IMAGE_GENERATION_PORT");
export const CONTENT_MODERATION_PORT = Symbol("CONTENT_MODERATION_PORT");
export const IMAGE_GENERATION_RUN_SERVICE = Symbol(
  "IMAGE_GENERATION_RUN_SERVICE",
);
