export const DATABASE_CLIENT = Symbol("DATABASE_CLIENT");
export const IDENTITY_REPOSITORY = Symbol("IDENTITY_REPOSITORY");
export const PUBLICATION_REPOSITORY = Symbol("PUBLICATION_REPOSITORY");
export const PUBLICATION_DRAFT_REPOSITORY = Symbol(
  "PUBLICATION_DRAFT_REPOSITORY",
);
export const RELIABLE_OPERATION_REPOSITORY = Symbol(
  "RELIABLE_OPERATION_REPOSITORY",
);
export const PUBLICATION_STATE_REPOSITORY = Symbol(
  "PUBLICATION_STATE_REPOSITORY",
);
export const PUBLICATION_PRODUCTION_REPOSITORY = Symbol(
  "PUBLICATION_PRODUCTION_REPOSITORY",
);
export const APPROVAL_SNAPSHOT_REPOSITORY = Symbol(
  "APPROVAL_SNAPSHOT_REPOSITORY",
);
export const MEDIA_ASSET_REPOSITORY = Symbol("MEDIA_ASSET_REPOSITORY");
export const ORGANIZATION_CONFIGURATION_REPOSITORY = Symbol(
  "ORGANIZATION_CONFIGURATION_REPOSITORY",
);
export const CONTENT_BRIEF_REQUEST_REPOSITORY = Symbol(
  "CONTENT_BRIEF_REQUEST_REPOSITORY",
);
export const CONTENT_BRIEF_RUN_REPOSITORY = Symbol(
  "CONTENT_BRIEF_RUN_REPOSITORY",
);
export const GENERATION_RUN_REQUEST_REPOSITORY = Symbol(
  "GENERATION_RUN_REQUEST_REPOSITORY",
);
export const GENERATION_RUN_REPOSITORY = Symbol("GENERATION_RUN_REPOSITORY");
