export const DATABASE_CLIENT = Symbol("DATABASE_CLIENT");
export const IDENTITY_REPOSITORY = Symbol("IDENTITY_REPOSITORY");
export const PUBLICATION_REPOSITORY = Symbol("PUBLICATION_REPOSITORY");
export const PUBLICATION_STATE_REPOSITORY = Symbol(
  "PUBLICATION_STATE_REPOSITORY",
);
export const APPROVAL_SNAPSHOT_REPOSITORY = Symbol(
  "APPROVAL_SNAPSHOT_REPOSITORY",
);
export const MEDIA_ASSET_REPOSITORY = Symbol("MEDIA_ASSET_REPOSITORY");
